name: Tag ersion
description: Tag new version with bump2version

inputs:
  user:
    description: 'User name of the GitHub user to push tags as'
    required: true
  email:
    description: 'Email of the GitHub user to push tags as'
    required: true


runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install bump2version

    - name: Tag version
      shell: bash
      run: |
        git fetch origin +refs/tags/*:refs/tags/*
        git config user.email ${{ inputs.email }}
        git config user.name ${{ inputs.user }}

        LABEL_QUERY='.data.repository.pullRequest.labels.nodes[].name'
        SELECT='select(. == "major" or . == "minor" or . == "patch")'
        BUMP_PART=$(jq --raw-output  "${LABEL_QUERY} | ${SELECT}" labels.json | sort | head -1)

        PR_QUERY='.data.repository.commit.associatedPullRequests.edges[0].node.title'
        TAG_MSG=$(jq --raw-output "${PR_QUERY}"  pr.json)

        bump2version --current-version $(git describe --abbrev=0) \
            --tag --tag-message "${TAG_MSG}" "${BUMP_PART}"

        git push --tags
        echo "Tagged version $(git describe --abbrev=0) and pushed back to repo"