name: Changelog updated?
on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize
    branches:
      - main
      - develop
jobs:
  call-changelog-check-workflow:
    uses: ./.github/workflows/reusable-changelog-check.yml
