on:
  workflow_call:

jobs:
  changelog-updated:
    if: ${{ ! contains(github.event.pull_request.labels.*.name, 'bumpless') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Changelog check
        run: |
          if git diff --quiet "origin/asdfasdf" -- CHANGELOG.md; then
            echo "Changelog not updated"
            exit 1
          fi
        shell: bash
