on:
  workflow_call:
    outputs:
      name:
        value: ${{ jobs.tag_info.outputs.name }}


jobs:
  tag_info:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.set_outputs.outputs.name }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set outputs
        id: set_outputs
        shell: bash -l {0}
        run: |
          git fetch origin +refs/tags/*:refs/tags/*
          export SDIST_VERSION=$(git describe)
          echo "name=${SDIST_VERSION}" >> $GITHUB_OUTPUT
