on:
  workflow_call:

jobs:
  changelog-updated:
    if: ${{ ! contains(github.event.pull_request.labels.*.name, 'bumpless') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Changelog check
        run: 'git branch -a && ! git diff --quiet ${{ github.event.pull_request.base.ref }} -- CHANGELOG.md'
        shell: bash
