on:
  workflow_call:
    inputs:
      conda_env_name:
        required: true
        type: string
      python_version:
        required: false
        default: '3.9'
        type: string
      method:
        description: 'The method used to generate the version number. Can be one of: `setup.py` or `setuptools_scm`'
        required: false
        default: 'setup.py'
        type: string
    outputs:
      version:
        value: ${{ jobs.version_info.outputs.version }}
      version_tag:
        value: ${{ jobs.version_info.outputs.version_tag }}



jobs:
  version_info:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_outputs.outputs.version }}
      version_tag: ${{ steps.set_outputs.outputs.version_tag }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          python-version: ${{ inputs.python_version }}
          activate-environment: ${{ inputs.conda_env_name }}
          environment-file: environment.yml

      - name: set outputs
        id: set_outputs
        shell: bash -l {0}
        run: |
          if [ "${{ inputs.method }}" == "setup.py" ]; then
            export SDIST_VERSION=$(python setup.py --version)
          elif [ "${{ inputs.method }}" == "setuptools_scm" ]; then
            export SDIST_VERSION=$(python -m setuptools_scm)
          fi
          echo "Version number: ${SDIST_VERSION}"
          echo "version=${SDIST_VERSION}" >> $GITHUB_OUTPUT
          echo "version_tag=${SDIST_VERSION/+/_}" >> $GITHUB_OUTPUT
