on:
  workflow_call:
    inputs:
      runner:
        required: false
        default: ubuntu-latest
        type: string

jobs:
  check-with-mypy:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml

      - name: Check with MyPy
        shell: bash -l {0}
        run: |
          mkdir .mypy_cache && mypy .
