on:
  workflow_call:
    inputs:
      runner:
        required: false
        default: ubuntu-latest
        type: string

jobs:
  check-with-ruff:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml

      - name: ruff check
        shell: bash -l {0}
        run: |
          ruff check --output-format=github || (echo 'Run `ruff check --fix` to automatically fix errors where possible.' && exit 1)

      - name: ruff format
        shell: bash -l {0}
        if: ${{ !cancelled() }}
        run: |
          ruff format --diff || (echo 'Run `ruff format` to automatically re-format.' && exit 1)
