on:
  workflow_call

jobs:
  bump-labeled:
    runs-on: ubuntu-latest
    steps:
      - name: Require Version Bump Labels
        uses: mheap/github-action-required-labels@v2
        with:
          mode: exactly
          count: 1
          labels: "major, minor, patch, bumpless"
