on:
  workflow_call:
    secrets:
      USER_TOKEN:
        required: true

jobs:
  changelog-udated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Changelog check
        uses: Zomzog/changelog-checker@v1.2.0
        with:
          fileName: CHANGELOG.md
          noChangelogLabel: bumpless
        env:
          GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}
