on:
  workflow_call:
    inputs:
      release_prefix:
        required: true
        type: string
      release_branch:
        required: false
        default: main
        type: string
      develop_branch:
        required: false
        default: develop
        type: string
      sync_pr_label:
        required: false
        default: tools-bot
        type: string
    secrets:
      USER_TOKEN:
        required: true

jobs:
  write-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.USER_TOKEN }}

      - name: Create Release
        uses: docker://antonyurchenko/git-release:v3.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}
          RELEASE_NAME_PREFIX: "${{ inputs.release_prefix }} "
          ALLOW_TAG_PREFIX: true

      - name: Attempt fast-forward develop from release
        run: |
          git fetch --prune
          git checkout ${{ inputs.develop_branch }} && git pull --ff-only
          git merge --ff-only origin/${{ inputs.release_branch }}
          git push

      - name: Open PR to bring release back to develop
        if: ${{ failure() }}
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ inputs.release_branch }}
          destination_branch: ${{ inputs.develop_branch }}
          pr_title: Pulling ${{ github.ref }} into ${{ inputs.develop_branch }}
          pr_body: Fast-forward of ${{ inputs.release_branch }} to ${{ inputs.develop_branch }} failed!
          pr_assignee: ${{ github.actor }}
          pr_label: ${{ inputs.sync_pr_label }}
          pr_draft: false
          pr_allow_empty: true
          github_token: ${{ secrets.USER_TOKEN }}
