on:
  workflow_call:

jobs:
  check-with-ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ruff

      - name: Ruff linting check
        run: ruff check --output-format=github .

      - name: Ruff format check
        run: ruff format --diff .
