on:
  workflow_call:

jobs:
  check-with-ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml

      - name: ruff check
        run: ruff check --output-format=github || (echo 'Run `ruff check --fix` to automatically fix errors where possible.' && exit 1)

      - name: ruff format
        if: ${{ !cancelled() }}
        run: ruff format --diff || (echo 'Run `ruff format` to automatically re-format.' && exit 1)
