on:
  workflow_call:
    inputs:
      additional_developer_items:
        required: false
        default: ""
        type: string
      additional_reviewer_items:
        required: false
        default: ""
        type: string
    secrets:
      USER_TOKEN:
        required: true


jobs:
  add-release-checklist-comment:
    runs-on: ubuntu-latest
    name: Add a comment with the release checklist
    steps:
      - uses: actions/checkout@v4

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ### Developer checklist

            - [ ] Indicated the level of changes to this package by affixing one of these labels:
              * major -- Major changes to the API that may break current workflows
              * minor -- Minor changes to the API that do not break current workflows
              * patch -- Patches and bugfixes for the current version that do not break current workflows
              * bumpless -- Changes to documentation, CI/CD pipelines, etc. that don't affect the software's version
            - [ ] (If applicable) Updated the dependencies and indicated any downstream changes that are required
            - [ ] Added/updated documentation for these changes
            - [ ] Added/updated tests for these changes
            ${{ inputs.additional_developer_items }}

            ### Reviewer checklist

            - [ ] Have all dependencies been updated?
            - [ ] Is the level of changes labeled appropriately?
            - [ ] Are all the changes described appropriately in `CHANGELOG.md`?
            - [ ] Has the documentation been adequately updated?
            - [ ] Are the tests adequate?
            ${{ inputs.additional_reviewer_items }}

          GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}
