name: Update Actions Examples

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to set all examples to'
        required: true
        type: string
  push:
    tags:
      - v*

jobs:
  call-git-object-name-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-git-object-name.yml@v0.9.0

  upate_actions_examples:
    needs: call-git-object-name-workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOOLS_BOT_PAK }}

      - name: Get version number
        env:
           INPUT_VERSION: ${{ github.event.inputs.version }}
           OBJECT_VERSION: ${{ needs.call-git-object-name-workflow.outputs.name }}
        run: |
          if [[ -z "${INPUT_VERSION}" ]]; then
            echo "ACTIONS_VERSION=${OBJECT_VERSION%%-*}" >> $GITHUB_ENV
          else
            echo "ACTIONS_VERSION=${INPUT_VERSION%%-*}" >> $GITHUB_ENV
          fi

      - name: Create update branch
        id: update
        run: |
          git config user.name "tools-bot"
          git config user.email "UAF-asf-apd@alaska.edu"

          export UPDATE_BRANCH=update-examples-to-${ACTIONS_VERSION}
          git switch -c ${UPDATE_BRANCH}
          
          export SEARCH_PATTERN='(ASFHyP3/actions/.github/workflows/.*.yml)@v[0-9]+\.[0-9]+\.[0-9]+'
          sed -i -r "s|$SEARCH_PATTERN|\1@${ACTIONS_VERSION}|g" README.md
          
          git commit -am "Bump actions example's version to ${ACTIONS_VERSION}"
          git push origin ${UPDATE_BRANCH}

      - name: Open PR
        env:
          PR_TITLE: Update Actions example versions to ${{ env.ACTIONS_VERSION }}
          PR_BODY: PR created by a new `v*` tag push event
          GH_TOKEN: ${{ secrets.TOOLS_BOT_PAK }}
        run: |
          gh pr create -t "${PR_TITLE}" -b "${PR_BODY}" -l tools-bot -l bumpless -B develop
